theme: jekyll-theme-cayman
title: Isabelle Quick Access Links
description: Quicklinks to all important sites related to the Isabelle theorem prover

collections:
  shortlinks:
    output: true
    permalink: /:name/
  addons:
    output: true
    permalink: /addons/:name/
  libraries:
    output: true
    permalink: /libraries/:name/

defaults:
  - scope:
      path: _shortlinks
      type: shortlinks
    values:
      layout: shortlink
  - scope:
      path: _addons
      type: addons
    values:
      layout: shortlink
  - scope:
      path: _libraries
      type: libraries
    values:
      layout: shortlink
